// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteJobReader is a Reader for the DeleteJob structure.
type DeleteJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteJobNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteJobNoContent creates a DeleteJobNoContent with default headers values
func NewDeleteJobNoContent() *DeleteJobNoContent {
	return &DeleteJobNoContent{}
}

/* DeleteJobNoContent describes a response with status code 204, with default header values.

Success
*/
type DeleteJobNoContent struct {
}

func (o *DeleteJobNoContent) Error() string {
	return fmt.Sprintf("[DELETE /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/jobs/{jobName}][%d] deleteJobNoContent ", 204)
}

func (o *DeleteJobNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobBadRequest creates a DeleteJobBadRequest with default headers values
func NewDeleteJobBadRequest() *DeleteJobBadRequest {
	return &DeleteJobBadRequest{}
}

/* DeleteJobBadRequest describes a response with status code 400, with default header values.

Invalid job
*/
type DeleteJobBadRequest struct {
}

func (o *DeleteJobBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/jobs/{jobName}][%d] deleteJobBadRequest ", 400)
}

func (o *DeleteJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobUnauthorized creates a DeleteJobUnauthorized with default headers values
func NewDeleteJobUnauthorized() *DeleteJobUnauthorized {
	return &DeleteJobUnauthorized{}
}

/* DeleteJobUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteJobUnauthorized struct {
}

func (o *DeleteJobUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/jobs/{jobName}][%d] deleteJobUnauthorized ", 401)
}

func (o *DeleteJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobForbidden creates a DeleteJobForbidden with default headers values
func NewDeleteJobForbidden() *DeleteJobForbidden {
	return &DeleteJobForbidden{}
}

/* DeleteJobForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteJobForbidden struct {
}

func (o *DeleteJobForbidden) Error() string {
	return fmt.Sprintf("[DELETE /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/jobs/{jobName}][%d] deleteJobForbidden ", 403)
}

func (o *DeleteJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteJobNotFound creates a DeleteJobNotFound with default headers values
func NewDeleteJobNotFound() *DeleteJobNotFound {
	return &DeleteJobNotFound{}
}

/* DeleteJobNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteJobNotFound struct {
}

func (o *DeleteJobNotFound) Error() string {
	return fmt.Sprintf("[DELETE /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/jobs/{jobName}][%d] deleteJobNotFound ", 404)
}

func (o *DeleteJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
