// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/radixapi/models"
)

// GetJobComponentDeploymentsReader is a Reader for the GetJobComponentDeployments structure.
type GetJobComponentDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobComponentDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobComponentDeploymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetJobComponentDeploymentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetJobComponentDeploymentsOK creates a GetJobComponentDeploymentsOK with default headers values
func NewGetJobComponentDeploymentsOK() *GetJobComponentDeploymentsOK {
	return &GetJobComponentDeploymentsOK{}
}

/* GetJobComponentDeploymentsOK describes a response with status code 200, with default header values.

Radix deployments
*/
type GetJobComponentDeploymentsOK struct {
	Payload []*models.DeploymentItem
}

func (o *GetJobComponentDeploymentsOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/deployments][%d] getJobComponentDeploymentsOK  %+v", 200, o.Payload)
}
func (o *GetJobComponentDeploymentsOK) GetPayload() []*models.DeploymentItem {
	return o.Payload
}

func (o *GetJobComponentDeploymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobComponentDeploymentsNotFound creates a GetJobComponentDeploymentsNotFound with default headers values
func NewGetJobComponentDeploymentsNotFound() *GetJobComponentDeploymentsNotFound {
	return &GetJobComponentDeploymentsNotFound{}
}

/* GetJobComponentDeploymentsNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetJobComponentDeploymentsNotFound struct {
}

func (o *GetJobComponentDeploymentsNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/deployments][%d] getJobComponentDeploymentsNotFound ", 404)
}

func (o *GetJobComponentDeploymentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
