// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StopBatchReader is a Reader for the StopBatch structure.
type StopBatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopBatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStopBatchNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStopBatchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewStopBatchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewStopBatchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStopBatchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopBatchNoContent creates a StopBatchNoContent with default headers values
func NewStopBatchNoContent() *StopBatchNoContent {
	return &StopBatchNoContent{}
}

/* StopBatchNoContent describes a response with status code 204, with default header values.

Success
*/
type StopBatchNoContent struct {
}

func (o *StopBatchNoContent) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/batches/{batchName}/stop][%d] stopBatchNoContent ", 204)
}

func (o *StopBatchNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopBatchBadRequest creates a StopBatchBadRequest with default headers values
func NewStopBatchBadRequest() *StopBatchBadRequest {
	return &StopBatchBadRequest{}
}

/* StopBatchBadRequest describes a response with status code 400, with default header values.

Invalid batch
*/
type StopBatchBadRequest struct {
}

func (o *StopBatchBadRequest) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/batches/{batchName}/stop][%d] stopBatchBadRequest ", 400)
}

func (o *StopBatchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopBatchUnauthorized creates a StopBatchUnauthorized with default headers values
func NewStopBatchUnauthorized() *StopBatchUnauthorized {
	return &StopBatchUnauthorized{}
}

/* StopBatchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type StopBatchUnauthorized struct {
}

func (o *StopBatchUnauthorized) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/batches/{batchName}/stop][%d] stopBatchUnauthorized ", 401)
}

func (o *StopBatchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopBatchForbidden creates a StopBatchForbidden with default headers values
func NewStopBatchForbidden() *StopBatchForbidden {
	return &StopBatchForbidden{}
}

/* StopBatchForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type StopBatchForbidden struct {
}

func (o *StopBatchForbidden) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/batches/{batchName}/stop][%d] stopBatchForbidden ", 403)
}

func (o *StopBatchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStopBatchNotFound creates a StopBatchNotFound with default headers values
func NewStopBatchNotFound() *StopBatchNotFound {
	return &StopBatchNotFound{}
}

/* StopBatchNotFound describes a response with status code 404, with default header values.

Not found
*/
type StopBatchNotFound struct {
}

func (o *StopBatchNotFound) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/jobcomponents/{jobComponentName}/batches/{batchName}/stop][%d] stopBatchNotFound ", 404)
}

func (o *StopBatchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
