// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new component API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for component API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ChangeEnvVar(params *ChangeEnvVarParams, authInfo runtime.ClientAuthInfoWriter) (*ChangeEnvVarOK, error)

	Components(params *ComponentsParams, authInfo runtime.ClientAuthInfoWriter) (*ComponentsOK, error)

	EnvVars(params *EnvVarsParams, authInfo runtime.ClientAuthInfoWriter) (*EnvVarsOK, error)

	GetOAuthPodLog(params *GetOAuthPodLogParams, authInfo runtime.ClientAuthInfoWriter) (*GetOAuthPodLogOK, error)

	Log(params *LogParams, authInfo runtime.ClientAuthInfoWriter) (*LogOK, error)

	ReplicaLog(params *ReplicaLogParams, authInfo runtime.ClientAuthInfoWriter) (*ReplicaLogOK, error)

	RestartComponent(params *RestartComponentParams, authInfo runtime.ClientAuthInfoWriter) (*RestartComponentOK, error)

	RestartOAuthAuxiliaryResource(params *RestartOAuthAuxiliaryResourceParams, authInfo runtime.ClientAuthInfoWriter) (*RestartOAuthAuxiliaryResourceOK, error)

	StartComponent(params *StartComponentParams, authInfo runtime.ClientAuthInfoWriter) (*StartComponentOK, error)

	StopComponent(params *StopComponentParams, authInfo runtime.ClientAuthInfoWriter) (*StopComponentOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ChangeEnvVar updates an environment variable
*/
func (a *Client) ChangeEnvVar(params *ChangeEnvVarParams, authInfo runtime.ClientAuthInfoWriter) (*ChangeEnvVarOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChangeEnvVarParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "changeEnvVar",
		Method:             "PATCH",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/envvars",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ChangeEnvVarReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChangeEnvVarOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for changeEnvVar: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Components gets components for a deployment
*/
func (a *Client) Components(params *ComponentsParams, authInfo runtime.ClientAuthInfoWriter) (*ComponentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewComponentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "components",
		Method:             "GET",
		PathPattern:        "/applications/{appName}/deployments/{deploymentName}/components",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ComponentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ComponentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for components: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  EnvVars gets environment variables for component
*/
func (a *Client) EnvVars(params *EnvVarsParams, authInfo runtime.ClientAuthInfoWriter) (*EnvVarsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEnvVarsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "envVars",
		Method:             "GET",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/envvars",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &EnvVarsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*EnvVarsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for envVars: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetOAuthPodLog gets logs for an oauth auxiliary resource pod
*/
func (a *Client) GetOAuthPodLog(params *GetOAuthPodLogParams, authInfo runtime.ClientAuthInfoWriter) (*GetOAuthPodLogOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetOAuthPodLogParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getOAuthPodLog",
		Method:             "GET",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/replicas/{podName}/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetOAuthPodLogReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetOAuthPodLogOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getOAuthPodLog: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Log gets logs from a deployed pod
*/
func (a *Client) Log(params *LogParams, authInfo runtime.ClientAuthInfoWriter) (*LogOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLogParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "log",
		Method:             "GET",
		PathPattern:        "/applications/{appName}/deployments/{deploymentName}/components/{componentName}/replicas/{podName}/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &LogReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LogOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for log: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ReplicaLog gets logs from a deployed pod
*/
func (a *Client) ReplicaLog(params *ReplicaLogParams, authInfo runtime.ClientAuthInfoWriter) (*ReplicaLogOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReplicaLogParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "replicaLog",
		Method:             "GET",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/replicas/{podName}/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ReplicaLogReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReplicaLogOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for replicaLog: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RestartComponent restarts a component stops running the component container pulls new image from image hub in radix configuration starts the container again using an up to date image
*/
func (a *Client) RestartComponent(params *RestartComponentParams, authInfo runtime.ClientAuthInfoWriter) (*RestartComponentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRestartComponentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "restartComponent",
		Method:             "POST",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/restart",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RestartComponentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RestartComponentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for restartComponent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RestartOAuthAuxiliaryResource restarts an auxiliary resource for a component
*/
func (a *Client) RestartOAuthAuxiliaryResource(params *RestartOAuthAuxiliaryResourceParams, authInfo runtime.ClientAuthInfoWriter) (*RestartOAuthAuxiliaryResourceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRestartOAuthAuxiliaryResourceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "restartOAuthAuxiliaryResource",
		Method:             "POST",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RestartOAuthAuxiliaryResourceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RestartOAuthAuxiliaryResourceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for restartOAuthAuxiliaryResource: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StartComponent starts component
*/
func (a *Client) StartComponent(params *StartComponentParams, authInfo runtime.ClientAuthInfoWriter) (*StartComponentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStartComponentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "startComponent",
		Method:             "POST",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/start",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &StartComponentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StartComponentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for startComponent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  StopComponent stops component
*/
func (a *Client) StopComponent(params *StopComponentParams, authInfo runtime.ClientAuthInfoWriter) (*StopComponentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStopComponentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stopComponent",
		Method:             "POST",
		PathPattern:        "/applications/{appName}/environments/{envName}/components/{componentName}/stop",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &StopComponentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*StopComponentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for stopComponent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
