// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RestartOAuthAuxiliaryResourceReader is a Reader for the RestartOAuthAuxiliaryResource structure.
type RestartOAuthAuxiliaryResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestartOAuthAuxiliaryResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRestartOAuthAuxiliaryResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRestartOAuthAuxiliaryResourceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRestartOAuthAuxiliaryResourceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRestartOAuthAuxiliaryResourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewRestartOAuthAuxiliaryResourceConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRestartOAuthAuxiliaryResourceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRestartOAuthAuxiliaryResourceOK creates a RestartOAuthAuxiliaryResourceOK with default headers values
func NewRestartOAuthAuxiliaryResourceOK() *RestartOAuthAuxiliaryResourceOK {
	return &RestartOAuthAuxiliaryResourceOK{}
}

/*RestartOAuthAuxiliaryResourceOK handles this case with default header values.

Auxiliary resource restarted ok
*/
type RestartOAuthAuxiliaryResourceOK struct {
}

func (o *RestartOAuthAuxiliaryResourceOK) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceOK ", 200)
}

func (o *RestartOAuthAuxiliaryResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartOAuthAuxiliaryResourceUnauthorized creates a RestartOAuthAuxiliaryResourceUnauthorized with default headers values
func NewRestartOAuthAuxiliaryResourceUnauthorized() *RestartOAuthAuxiliaryResourceUnauthorized {
	return &RestartOAuthAuxiliaryResourceUnauthorized{}
}

/*RestartOAuthAuxiliaryResourceUnauthorized handles this case with default header values.

Unauthorized
*/
type RestartOAuthAuxiliaryResourceUnauthorized struct {
}

func (o *RestartOAuthAuxiliaryResourceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceUnauthorized ", 401)
}

func (o *RestartOAuthAuxiliaryResourceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartOAuthAuxiliaryResourceForbidden creates a RestartOAuthAuxiliaryResourceForbidden with default headers values
func NewRestartOAuthAuxiliaryResourceForbidden() *RestartOAuthAuxiliaryResourceForbidden {
	return &RestartOAuthAuxiliaryResourceForbidden{}
}

/*RestartOAuthAuxiliaryResourceForbidden handles this case with default header values.

Forbidden
*/
type RestartOAuthAuxiliaryResourceForbidden struct {
}

func (o *RestartOAuthAuxiliaryResourceForbidden) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceForbidden ", 403)
}

func (o *RestartOAuthAuxiliaryResourceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartOAuthAuxiliaryResourceNotFound creates a RestartOAuthAuxiliaryResourceNotFound with default headers values
func NewRestartOAuthAuxiliaryResourceNotFound() *RestartOAuthAuxiliaryResourceNotFound {
	return &RestartOAuthAuxiliaryResourceNotFound{}
}

/*RestartOAuthAuxiliaryResourceNotFound handles this case with default header values.

Not found
*/
type RestartOAuthAuxiliaryResourceNotFound struct {
}

func (o *RestartOAuthAuxiliaryResourceNotFound) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceNotFound ", 404)
}

func (o *RestartOAuthAuxiliaryResourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartOAuthAuxiliaryResourceConflict creates a RestartOAuthAuxiliaryResourceConflict with default headers values
func NewRestartOAuthAuxiliaryResourceConflict() *RestartOAuthAuxiliaryResourceConflict {
	return &RestartOAuthAuxiliaryResourceConflict{}
}

/*RestartOAuthAuxiliaryResourceConflict handles this case with default header values.

Conflict
*/
type RestartOAuthAuxiliaryResourceConflict struct {
}

func (o *RestartOAuthAuxiliaryResourceConflict) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceConflict ", 409)
}

func (o *RestartOAuthAuxiliaryResourceConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRestartOAuthAuxiliaryResourceInternalServerError creates a RestartOAuthAuxiliaryResourceInternalServerError with default headers values
func NewRestartOAuthAuxiliaryResourceInternalServerError() *RestartOAuthAuxiliaryResourceInternalServerError {
	return &RestartOAuthAuxiliaryResourceInternalServerError{}
}

/*RestartOAuthAuxiliaryResourceInternalServerError handles this case with default header values.

Internal server error
*/
type RestartOAuthAuxiliaryResourceInternalServerError struct {
}

func (o *RestartOAuthAuxiliaryResourceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/environments/{envName}/components/{componentName}/aux/oauth/restart][%d] restartOAuthAuxiliaryResourceInternalServerError ", 500)
}

func (o *RestartOAuthAuxiliaryResourceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
