// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/radixapi/models"
)

// TriggerPipelineDeployReader is a Reader for the TriggerPipelineDeploy structure.
type TriggerPipelineDeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TriggerPipelineDeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTriggerPipelineDeployOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewTriggerPipelineDeployNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTriggerPipelineDeployOK creates a TriggerPipelineDeployOK with default headers values
func NewTriggerPipelineDeployOK() *TriggerPipelineDeployOK {
	return &TriggerPipelineDeployOK{}
}

/* TriggerPipelineDeployOK describes a response with status code 200, with default header values.

Successful trigger pipeline
*/
type TriggerPipelineDeployOK struct {
	Payload *models.JobSummary
}

func (o *TriggerPipelineDeployOK) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/pipelines/deploy][%d] triggerPipelineDeployOK  %+v", 200, o.Payload)
}
func (o *TriggerPipelineDeployOK) GetPayload() *models.JobSummary {
	return o.Payload
}

func (o *TriggerPipelineDeployOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTriggerPipelineDeployNotFound creates a TriggerPipelineDeployNotFound with default headers values
func NewTriggerPipelineDeployNotFound() *TriggerPipelineDeployNotFound {
	return &TriggerPipelineDeployNotFound{}
}

/* TriggerPipelineDeployNotFound describes a response with status code 404, with default header values.

Not found
*/
type TriggerPipelineDeployNotFound struct {
}

func (o *TriggerPipelineDeployNotFound) Error() string {
	return fmt.Sprintf("[POST /applications/{appName}/pipelines/deploy][%d] triggerPipelineDeployNotFound ", 404)
}

func (o *TriggerPipelineDeployNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
