// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationPatchRequest ApplicationPatchRequest contains fields that can be patched on a registration
//
// swagger:model ApplicationPatchRequest
type ApplicationPatchRequest struct {

	// AdGroups the groups that should be able to access the application
	AdGroups []string `json:"adGroups"`

	// ConfigBranch information
	ConfigBranch string `json:"configBranch,omitempty"`

	// MachineUser is used for interacting directly with Radix API
	MachineUser *bool `json:"machineUser,omitempty"`

	// Owner of the application - should be an email
	Owner string `json:"owner,omitempty"`

	// Repository the github repository
	Repository string `json:"repository,omitempty"`

	// WBS information
	WBS string `json:"wbs,omitempty"`
}

// Validate validates this application patch request
func (m *ApplicationPatchRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationPatchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationPatchRequest) UnmarshalBinary(b []byte) error {
	var res ApplicationPatchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
