// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobStatus JobStatus holds general information about job status
//
// swagger:model JobStatus
type JobStatus struct {

	// Created timestamp
	// Example: 2006-01-02T15:04:05Z
	// Required: true
	Created *string `json:"created"`

	// Ended timestamp
	// Example: 2006-01-02T15:04:05Z
	Ended string `json:"ended,omitempty"`

	// Status message, if any, of the job
	// Example: \"Error occurred\
	Message string `json:"message,omitempty"`

	// Name of the job
	// Example: calculator
	// Required: true
	Name *string `json:"name"`

	// Started timestamp
	// Example: 2006-01-02T15:04:05Z
	Started string `json:"started,omitempty"`

	// Status of the job
	// Example: Waiting
	// Enum: [Waiting Running Succeeded Stopping Stopped Failed]
	Status string `json:"status,omitempty"`
}

// Validate validates this job status
func (m *JobStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobStatus) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *JobStatus) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var jobStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Waiting","Running","Succeeded","Stopping","Stopped","Failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		jobStatusTypeStatusPropEnum = append(jobStatusTypeStatusPropEnum, v)
	}
}

const (

	// JobStatusStatusWaiting captures enum value "Waiting"
	JobStatusStatusWaiting string = "Waiting"

	// JobStatusStatusRunning captures enum value "Running"
	JobStatusStatusRunning string = "Running"

	// JobStatusStatusSucceeded captures enum value "Succeeded"
	JobStatusStatusSucceeded string = "Succeeded"

	// JobStatusStatusStopping captures enum value "Stopping"
	JobStatusStatusStopping string = "Stopping"

	// JobStatusStatusStopped captures enum value "Stopped"
	JobStatusStatusStopped string = "Stopped"

	// JobStatusStatusFailed captures enum value "Failed"
	JobStatusStatusFailed string = "Failed"
)

// prop value enum
func (m *JobStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, jobStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *JobStatus) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this job status based on context it is used
func (m *JobStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobStatus) UnmarshalBinary(b []byte) error {
	var res JobStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
