// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ScanStatus ScanStatus defines the statuys of the vulnerability scanning
//
// swagger:model ScanStatus
type ScanStatus string

// Validate validates this scan status
func (m ScanStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scan status based on context it is used
func (m ScanStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
