// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// StatusReason status reason
//
// swagger:model StatusReason
type StatusReason string

// Validate validates this status reason
func (m StatusReason) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this status reason based on context it is used
func (m StatusReason) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
