// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/models"
)

// GetPipelineJobStepScanOutputReader is a Reader for the GetPipelineJobStepScanOutput structure.
type GetPipelineJobStepScanOutputReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineJobStepScanOutputReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineJobStepScanOutputOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPipelineJobStepScanOutputUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPipelineJobStepScanOutputNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPipelineJobStepScanOutputOK creates a GetPipelineJobStepScanOutputOK with default headers values
func NewGetPipelineJobStepScanOutputOK() *GetPipelineJobStepScanOutputOK {
	return &GetPipelineJobStepScanOutputOK{}
}

/* GetPipelineJobStepScanOutputOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetPipelineJobStepScanOutputOK struct {
	Payload []*models.Vulnerability
}

func (o *GetPipelineJobStepScanOutputOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/steps/{stepName}/output/scan][%d] getPipelineJobStepScanOutputOK  %+v", 200, o.Payload)
}
func (o *GetPipelineJobStepScanOutputOK) GetPayload() []*models.Vulnerability {
	return o.Payload
}

func (o *GetPipelineJobStepScanOutputOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineJobStepScanOutputUnauthorized creates a GetPipelineJobStepScanOutputUnauthorized with default headers values
func NewGetPipelineJobStepScanOutputUnauthorized() *GetPipelineJobStepScanOutputUnauthorized {
	return &GetPipelineJobStepScanOutputUnauthorized{}
}

/* GetPipelineJobStepScanOutputUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetPipelineJobStepScanOutputUnauthorized struct {
}

func (o *GetPipelineJobStepScanOutputUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/steps/{stepName}/output/scan][%d] getPipelineJobStepScanOutputUnauthorized ", 401)
}

func (o *GetPipelineJobStepScanOutputUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPipelineJobStepScanOutputNotFound creates a GetPipelineJobStepScanOutputNotFound with default headers values
func NewGetPipelineJobStepScanOutputNotFound() *GetPipelineJobStepScanOutputNotFound {
	return &GetPipelineJobStepScanOutputNotFound{}
}

/* GetPipelineJobStepScanOutputNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetPipelineJobStepScanOutputNotFound struct {
}

func (o *GetPipelineJobStepScanOutputNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/steps/{stepName}/output/scan][%d] getPipelineJobStepScanOutputNotFound ", 404)
}

func (o *GetPipelineJobStepScanOutputNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
