// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPipelineJobStepLogsReader is a Reader for the GetPipelineJobStepLogs structure.
type GetPipelineJobStepLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPipelineJobStepLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPipelineJobStepLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPipelineJobStepLogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPipelineJobStepLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPipelineJobStepLogsOK creates a GetPipelineJobStepLogsOK with default headers values
func NewGetPipelineJobStepLogsOK() *GetPipelineJobStepLogsOK {
	return &GetPipelineJobStepLogsOK{}
}

/*GetPipelineJobStepLogsOK handles this case with default header values.

Job step log
*/
type GetPipelineJobStepLogsOK struct {
	Payload string
}

func (o *GetPipelineJobStepLogsOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsOK  %+v", 200, o.Payload)
}

func (o *GetPipelineJobStepLogsOK) GetPayload() string {
	return o.Payload
}

func (o *GetPipelineJobStepLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPipelineJobStepLogsUnauthorized creates a GetPipelineJobStepLogsUnauthorized with default headers values
func NewGetPipelineJobStepLogsUnauthorized() *GetPipelineJobStepLogsUnauthorized {
	return &GetPipelineJobStepLogsUnauthorized{}
}

/*GetPipelineJobStepLogsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPipelineJobStepLogsUnauthorized struct {
}

func (o *GetPipelineJobStepLogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsUnauthorized ", 401)
}

func (o *GetPipelineJobStepLogsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPipelineJobStepLogsNotFound creates a GetPipelineJobStepLogsNotFound with default headers values
func NewGetPipelineJobStepLogsNotFound() *GetPipelineJobStepLogsNotFound {
	return &GetPipelineJobStepLogsNotFound{}
}

/*GetPipelineJobStepLogsNotFound handles this case with default header values.

Not found
*/
type GetPipelineJobStepLogsNotFound struct {
}

func (o *GetPipelineJobStepLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/logs/{stepName}][%d] getPipelineJobStepLogsNotFound ", 404)
}

func (o *GetPipelineJobStepLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
