// Code generated by go-swagger; DO NOT EDIT.

package pipeline_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/models"
)

// GetTektonPipelineRunReader is a Reader for the GetTektonPipelineRun structure.
type GetTektonPipelineRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTektonPipelineRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTektonPipelineRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetTektonPipelineRunUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTektonPipelineRunNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTektonPipelineRunOK creates a GetTektonPipelineRunOK with default headers values
func NewGetTektonPipelineRunOK() *GetTektonPipelineRunOK {
	return &GetTektonPipelineRunOK{}
}

/*GetTektonPipelineRunOK handles this case with default header values.

List of Pipeline Runs
*/
type GetTektonPipelineRunOK struct {
	Payload *models.PipelineRun
}

func (o *GetTektonPipelineRunOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/pipelineruns/{pipelineRunName}][%d] getTektonPipelineRunOK  %+v", 200, o.Payload)
}

func (o *GetTektonPipelineRunOK) GetPayload() *models.PipelineRun {
	return o.Payload
}

func (o *GetTektonPipelineRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PipelineRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTektonPipelineRunUnauthorized creates a GetTektonPipelineRunUnauthorized with default headers values
func NewGetTektonPipelineRunUnauthorized() *GetTektonPipelineRunUnauthorized {
	return &GetTektonPipelineRunUnauthorized{}
}

/*GetTektonPipelineRunUnauthorized handles this case with default header values.

Unauthorized
*/
type GetTektonPipelineRunUnauthorized struct {
}

func (o *GetTektonPipelineRunUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/pipelineruns/{pipelineRunName}][%d] getTektonPipelineRunUnauthorized ", 401)
}

func (o *GetTektonPipelineRunUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTektonPipelineRunNotFound creates a GetTektonPipelineRunNotFound with default headers values
func NewGetTektonPipelineRunNotFound() *GetTektonPipelineRunNotFound {
	return &GetTektonPipelineRunNotFound{}
}

/*GetTektonPipelineRunNotFound handles this case with default header values.

Not found
*/
type GetTektonPipelineRunNotFound struct {
}

func (o *GetTektonPipelineRunNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/jobs/{jobName}/pipelineruns/{pipelineRunName}][%d] getTektonPipelineRunNotFound ", 404)
}

func (o *GetTektonPipelineRunNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
