// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BatchEvent BatchEvent holds general information about batch event on change of status
//
// swagger:model BatchEvent
type BatchEvent struct {

	// BatchName Optional Batch ID of a job
	// Example: 'batch1'
	BatchName string `json:"batchName,omitempty"`

	// BatchType Single job or multiple jobs batch
	// Example: \"job\
	BatchType string `json:"batchType,omitempty"`

	// Created timestamp
	// Example: 2006-01-02T15:04:05Z
	// Required: true
	Created *string `json:"created"`

	// Ended timestamp
	// Example: 2006-01-02T15:04:05Z
	Ended string `json:"ended,omitempty"`

	// JobId Optional ID of a job
	// Example: 'job1'
	JobID string `json:"jobId,omitempty"`

	// JobStatuses of the jobs in the batch
	JobStatuses []*JobStatus `json:"jobStatuses"`

	// Message, if any, of the job
	// Example: \"Error occurred\
	Message string `json:"message,omitempty"`

	// Name of the job
	// Example: calculator
	// Required: true
	Name *string `json:"name"`

	// Started timestamp
	// Example: 2006-01-02T15:04:05Z
	Started string `json:"started,omitempty"`

	// Status of the job
	// Example: Waiting
	// Enum: [Waiting Running Succeeded Stopping Stopped Failed DeadlineExceeded]
	Status string `json:"status,omitempty"`

	// event
	// Required: true
	Event *Event `json:"event"`
}

// Validate validates this batch event
func (m *BatchEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobStatuses(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BatchEvent) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *BatchEvent) validateJobStatuses(formats strfmt.Registry) error {
	if swag.IsZero(m.JobStatuses) { // not required
		return nil
	}

	for i := 0; i < len(m.JobStatuses); i++ {
		if swag.IsZero(m.JobStatuses[i]) { // not required
			continue
		}

		if m.JobStatuses[i] != nil {
			if err := m.JobStatuses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("jobStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("jobStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BatchEvent) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var batchEventTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Waiting","Running","Succeeded","Stopping","Stopped","Failed","DeadlineExceeded"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		batchEventTypeStatusPropEnum = append(batchEventTypeStatusPropEnum, v)
	}
}

const (

	// BatchEventStatusWaiting captures enum value "Waiting"
	BatchEventStatusWaiting string = "Waiting"

	// BatchEventStatusRunning captures enum value "Running"
	BatchEventStatusRunning string = "Running"

	// BatchEventStatusSucceeded captures enum value "Succeeded"
	BatchEventStatusSucceeded string = "Succeeded"

	// BatchEventStatusStopping captures enum value "Stopping"
	BatchEventStatusStopping string = "Stopping"

	// BatchEventStatusStopped captures enum value "Stopped"
	BatchEventStatusStopped string = "Stopped"

	// BatchEventStatusFailed captures enum value "Failed"
	BatchEventStatusFailed string = "Failed"

	// BatchEventStatusDeadlineExceeded captures enum value "DeadlineExceeded"
	BatchEventStatusDeadlineExceeded string = "DeadlineExceeded"
)

// prop value enum
func (m *BatchEvent) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, batchEventTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BatchEvent) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *BatchEvent) validateEvent(formats strfmt.Registry) error {

	if err := validate.Required("event", "body", m.Event); err != nil {
		return err
	}

	if err := validate.Required("event", "body", m.Event); err != nil {
		return err
	}

	if m.Event != nil {
		if err := m.Event.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this batch event based on the context it is used
func (m *BatchEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateJobStatuses(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEvent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BatchEvent) contextValidateJobStatuses(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.JobStatuses); i++ {

		if m.JobStatuses[i] != nil {

			if swag.IsZero(m.JobStatuses[i]) { // not required
				return nil
			}

			if err := m.JobStatuses[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("jobStatuses" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("jobStatuses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BatchEvent) contextValidateEvent(ctx context.Context, formats strfmt.Registry) error {

	if m.Event != nil {

		if err := m.Event.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("event")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("event")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BatchEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BatchEvent) UnmarshalBinary(b []byte) error {
	var res BatchEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
