// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// EnvVars EnvVars Map of environment variables in the form '<envvarname>: <value>'
//
// swagger:model EnvVars
type EnvVars map[string]string

// Validate validates this env vars
func (m EnvVars) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this env vars based on context it is used
func (m EnvVars) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
