// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RadixJobComponentConfig RadixJobComponentConfig holds description of RadixJobComponent
//
// swagger:model RadixJobComponentConfig
type RadixJobComponentConfig struct {

	// BackoffLimit defines attempts to restart job if it fails. Corresponds to BackoffLimit in K8s.
	BackoffLimit int32 `json:"backoffLimit,omitempty"`

	// ImageTagName defines the image tag name to use for the job image
	ImageTagName string `json:"imageTagName,omitempty"`

	// Node defines node attributes, where container should be scheduled
	Node interface{} `json:"node,omitempty"`

	// Resource describes the compute resource requirements.
	Resources interface{} `json:"resources,omitempty"`

	// TimeLimitSeconds defines maximum job run time. Corresponds to ActiveDeadlineSeconds in K8s.
	TimeLimitSeconds int64 `json:"timeLimitSeconds,omitempty"`
}

// Validate validates this radix job component config
func (m *RadixJobComponentConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this radix job component config based on context it is used
func (m *RadixJobComponentConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RadixJobComponentConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RadixJobComponentConfig) UnmarshalBinary(b []byte) error {
	var res RadixJobComponentConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
