apiVersion: v1
name: radix-cicd-canary
version: 1.1.14
appVersion: 1.1.14
kubeVersion: ">=1.g22.0"
description: Radix CICD Canary
keywords:
  - radix
home: radix.equinor.com
sources:
  - https://github.com/equinor/radix-cicd-canary
maintainers: 
  - name: Omnia Radix
    email: Radix@StatoilSRM.onmicrosoft.com
deprecated: false