# Default values for radix-cicd-canary
clusterFQDN: xx

image:
  repository: xx
  tag: xx
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 5000
  annotations: {}

impersonate:
  user: t_iknu@equinor.com

deployKey:
  public: xx
  private: xx

deployKeyCanary3:
  public: xx
  private: xx

deployKeyCanary4:
  public: xx
  private: xx

privateImageHub:
  password: xx

clusterType: development

radixGroups:
  user: "64b28659-4fe4-4222-8497-85dd7e43e25b"
  playground: "4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31"

radixApiPrefix: server-radix-api-prod
radixWebhookPrefix: webhook-radix-github-webhook-prod
clusterFqdn: weekly-27.dev.radix.equinor.com
timeoutOfTest: 1200
sleepIntervalBetweenChecks: 5
sleepIntervalTestRuns: 300
nspSleepInterval: 15

resources:
  limits:
    cpu: 2000m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi