apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
data:
  impersonateGroup: {{ include "cicd-canary.platformUserGroup" . | quote }}
  impersonateUser: {{ .Values.impersonate.user }}
  publicKey: {{ .Values.deployKey.public }}
  privateKeyBase64: {{ .Values.deployKey.private }}
  publicKeyCanary3: {{ .Values.deployKeyCanary3.public }}
  privateKeyCanary3Base64: {{ .Values.deployKeyCanary3.private }}
  publicKeyCanary4: {{ .Values.deployKeyCanary4.public }}
  privateKeyCanary4Base64: {{ .Values.deployKeyCanary4.private }}
  radixApiPrefix: {{ .Values.radixApiPrefix}}
  radixWebhookPrefix: {{ .Values.radixWebhookPrefix}}
  clusterFqdn: {{ .Values.clusterFqdn}}
  timeoutOfTest: {{ .Values.timeoutOfTest | quote }}
  sleepIntervalBetweenChecks: {{ .Values.sleepIntervalBetweenChecks | quote }}
  sleepIntervalTestRuns: {{ .Values.sleepIntervalTestRuns | quote }}
  nspSleepInterval: {{ .Values.nspSleepInterval | quote }}
  nspDNSLookupTimeout: {{ .Values.nspDNSLookupTimeout | quote }}
  nspNSPReachIngressTimeout: {{ .Values.nspNSPReachIngressTimeout | quote }}
  nspNSPReachServiceTimeout: {{ .Values.nspNSPReachServiceTimeout | quote }}
  privateImageHubPassword: {{ .Values.privateImageHub.password }}
  nspLongSleepInterval: {{ .Values.nspLongSleepInterval | quote }}
  networkPolicyCanaryAppName: {{ .Values.networkPolicyCanaryAppName }}
  networkPolicyCanaryJobComponentName: {{ .Values.networkPolicyCanaryJobComponentName }}
  networkPolicyCanaryPassword: {{ .Values.networkPolicyCanary.password }}
  appAdminGroup: {{ .Values.appAdminGroup | quote }}
  appReaderGroup: {{ .Values.appReaderGroup | quote }}
