apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cicd-canary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cicd-canary.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "cicd-canary.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          env:
            {{- if and .Values.env .Values.env.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

