apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cicd-canary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cicd-canary.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "cicd-canary.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
          - 1000
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: LOG_LEVEL
              value: DEBUG
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
