apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
  name: {{ template "cicd-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 5s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "cicd-canary.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations}}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
  name: {{ template "cicd-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 5000
    protocol: TCP
    targetPort: metrics
  selector:
    matchLabels:
      {{- include "cicd-canary.selectorLabels" . | nindent 6 }}
  type: ClusterIP
