apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: radix-cicd-canary
  name: radix-cicd-canary
  namespace: radix-cicd-canary
spec:
  endpoints:
  - interval: 5s
    port: metrics
  namespaceSelector:
    matchNames:
    - radix-cicd-canary
  selector:
    matchLabels:
      app: radix-cicd-canary
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radix-cicd-canary
  name: radix-cicd-canary
  namespace: radix-cicd-canary
spec:
  ports:
  - name: metrics
    port: 5000
    protocol: TCP
    targetPort: metrics
  selector:
    app: radix-cicd-canary
  type: ClusterIP