apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: [{{ .Values.impersonate.user }}]
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
  {{if eq .Values.clusterType "playground"}}
  resourceNames: [{{ .Values.radixGroups.playground }}]
  {{else}}
  resourceNames: [{{ .Values.radixGroups.user }}]
  {{end}}
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  resourceNames:
  - canarycicd-test1
  - canarycicd-test2
  - canarycicd-test3
  - canarycicd-test4
  verbs:
  - get     # required for testing ad-group updates using service account
  - update  # required for testing ad-group updates using service account
  - patch   # required for testing ad-group updates using service account
  - delete  # required for testing ad-group updates using service account
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cicd-canary.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "cicd-canary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "deployment-scaler"
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps/v1"]
    resources: ["deployments.apps"]
    verbs:
     - "update"
     - "patch"
    resourceNames: ["{{ .Chart.Name }}"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "deployment-scaler"
  labels: {{- include "cicd-canary.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "deployment-scaler"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.servicePrincipalId }}