kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: [{{ .Values.impersonate.user }}]
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
  {{if eq .Values.clusterType "playground"}}
  resourceNames: [{{ .Values.radixGroups.playground }}]
  {{else}}
  resourceNames: [{{ .Values.radixGroups.user }}]
  {{end}}
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  verbs:
  - get    # required for testing ad-group updates using service account
  - update # required for testing ad-group updates using service account
  - patch  # required for testing ad-group updates using service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Chart.Name }}"
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}