apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: [{{ .Values.impersonate.user }}]
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
  resourceNames:
  - {{ required ".Values.radixGroups.user is required" .Values.radixGroups.user | quote }}
  - {{ .Values.appAdminGroup | quote }}
  - {{ .Values.appReaderGroup | quote }}
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  resourceNames:
  - canarycicd-test1
  - canarycicd-test2
  - canarycicd-test3
  - canarycicd-test4
  verbs:
  - get     # required for testing ad-group updates using service account
  - update  # required for testing ad-group updates using service account
  - patch   # required for testing ad-group updates using service account
  - delete  # required for testing ad-group updates using service account
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cicd-canary.fullname" . }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cicd-canary.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "cicd-canary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
