apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cicd-canary.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cicd-canary.labels" . | nindent 4 }}
