// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/jobserver/models"
)

// DeleteJobReader is a Reader for the DeleteJob structure.
type DeleteJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteJobOK creates a DeleteJobOK with default headers values
func NewDeleteJobOK() *DeleteJobOK {
	return &DeleteJobOK{}
}

/* DeleteJobOK describes a response with status code 200, with default header values.

Successful delete job
*/
type DeleteJobOK struct {
	Payload *models.Status
}

func (o *DeleteJobOK) Error() string {
	return fmt.Sprintf("[DELETE /jobs/{jobName}][%d] deleteJobOK  %+v", 200, o.Payload)
}
func (o *DeleteJobOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobNotFound creates a DeleteJobNotFound with default headers values
func NewDeleteJobNotFound() *DeleteJobNotFound {
	return &DeleteJobNotFound{}
}

/* DeleteJobNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteJobNotFound struct {
	Payload *models.Status
}

func (o *DeleteJobNotFound) Error() string {
	return fmt.Sprintf("[DELETE /jobs/{jobName}][%d] deleteJobNotFound  %+v", 404, o.Payload)
}
func (o *DeleteJobNotFound) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteJobInternalServerError creates a DeleteJobInternalServerError with default headers values
func NewDeleteJobInternalServerError() *DeleteJobInternalServerError {
	return &DeleteJobInternalServerError{}
}

/* DeleteJobInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteJobInternalServerError struct {
	Payload *models.Status
}

func (o *DeleteJobInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /jobs/{jobName}][%d] deleteJobInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteJobInternalServerError) GetPayload() *models.Status {
	return o.Payload
}

func (o *DeleteJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
