// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/jobserver/models"
)

// StopJobReader is a Reader for the StopJob structure.
type StopJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewStopJobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewStopJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStopJobOK creates a StopJobOK with default headers values
func NewStopJobOK() *StopJobOK {
	return &StopJobOK{}
}

/* StopJobOK describes a response with status code 200, with default header values.

Successful delete job
*/
type StopJobOK struct {
	Payload *models.Status
}

func (o *StopJobOK) Error() string {
	return fmt.Sprintf("[POST /jobs/{jobName}/stop][%d] stopJobOK  %+v", 200, o.Payload)
}
func (o *StopJobOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *StopJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopJobNotFound creates a StopJobNotFound with default headers values
func NewStopJobNotFound() *StopJobNotFound {
	return &StopJobNotFound{}
}

/* StopJobNotFound describes a response with status code 404, with default header values.

Not found
*/
type StopJobNotFound struct {
	Payload *models.Status
}

func (o *StopJobNotFound) Error() string {
	return fmt.Sprintf("[POST /jobs/{jobName}/stop][%d] stopJobNotFound  %+v", 404, o.Payload)
}
func (o *StopJobNotFound) GetPayload() *models.Status {
	return o.Payload
}

func (o *StopJobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopJobInternalServerError creates a StopJobInternalServerError with default headers values
func NewStopJobInternalServerError() *StopJobInternalServerError {
	return &StopJobInternalServerError{}
}

/* StopJobInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type StopJobInternalServerError struct {
	Payload *models.Status
}

func (o *StopJobInternalServerError) Error() string {
	return fmt.Sprintf("[POST /jobs/{jobName}/stop][%d] stopJobInternalServerError  %+v", 500, o.Payload)
}
func (o *StopJobInternalServerError) GetPayload() *models.Status {
	return o.Payload
}

func (o *StopJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
