// Code generated by go-swagger; DO NOT EDIT.

package batch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/jobserver/models"
)

// NewCreateBatchParams creates a new CreateBatchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBatchParams() *CreateBatchParams {
	return &CreateBatchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBatchParamsWithTimeout creates a new CreateBatchParams object
// with the ability to set a timeout on a request.
func NewCreateBatchParamsWithTimeout(timeout time.Duration) *CreateBatchParams {
	return &CreateBatchParams{
		timeout: timeout,
	}
}

// NewCreateBatchParamsWithContext creates a new CreateBatchParams object
// with the ability to set a context for a request.
func NewCreateBatchParamsWithContext(ctx context.Context) *CreateBatchParams {
	return &CreateBatchParams{
		Context: ctx,
	}
}

// NewCreateBatchParamsWithHTTPClient creates a new CreateBatchParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBatchParamsWithHTTPClient(client *http.Client) *CreateBatchParams {
	return &CreateBatchParams{
		HTTPClient: client,
	}
}

/*
CreateBatchParams contains all the parameters to send to the API endpoint

	for the create batch operation.

	Typically these are written to a http.Request.
*/
type CreateBatchParams struct {

	/* BatchCreation.

	   Batch to create
	*/
	BatchCreation *models.BatchScheduleDescription

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBatchParams) WithDefaults() *CreateBatchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBatchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create batch params
func (o *CreateBatchParams) WithTimeout(timeout time.Duration) *CreateBatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create batch params
func (o *CreateBatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create batch params
func (o *CreateBatchParams) WithContext(ctx context.Context) *CreateBatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create batch params
func (o *CreateBatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create batch params
func (o *CreateBatchParams) WithHTTPClient(client *http.Client) *CreateBatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create batch params
func (o *CreateBatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBatchCreation adds the batchCreation to the create batch params
func (o *CreateBatchParams) WithBatchCreation(batchCreation *models.BatchScheduleDescription) *CreateBatchParams {
	o.SetBatchCreation(batchCreation)
	return o
}

// SetBatchCreation adds the batchCreation to the create batch params
func (o *CreateBatchParams) SetBatchCreation(batchCreation *models.BatchScheduleDescription) {
	o.BatchCreation = batchCreation
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BatchCreation != nil {
		if err := r.SetBodyParam(o.BatchCreation); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
