// Code generated by go-swagger; DO NOT EDIT.

package batch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBatchParams creates a new GetBatchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBatchParams() *GetBatchParams {
	return &GetBatchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBatchParamsWithTimeout creates a new GetBatchParams object
// with the ability to set a timeout on a request.
func NewGetBatchParamsWithTimeout(timeout time.Duration) *GetBatchParams {
	return &GetBatchParams{
		timeout: timeout,
	}
}

// NewGetBatchParamsWithContext creates a new GetBatchParams object
// with the ability to set a context for a request.
func NewGetBatchParamsWithContext(ctx context.Context) *GetBatchParams {
	return &GetBatchParams{
		Context: ctx,
	}
}

// NewGetBatchParamsWithHTTPClient creates a new GetBatchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBatchParamsWithHTTPClient(client *http.Client) *GetBatchParams {
	return &GetBatchParams{
		HTTPClient: client,
	}
}

/* GetBatchParams contains all the parameters to send to the API endpoint
   for the get batch operation.

   Typically these are written to a http.Request.
*/
type GetBatchParams struct {

	/* BatchName.

	   Name of batch
	*/
	BatchName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBatchParams) WithDefaults() *GetBatchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBatchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get batch params
func (o *GetBatchParams) WithTimeout(timeout time.Duration) *GetBatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get batch params
func (o *GetBatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get batch params
func (o *GetBatchParams) WithContext(ctx context.Context) *GetBatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get batch params
func (o *GetBatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get batch params
func (o *GetBatchParams) WithHTTPClient(client *http.Client) *GetBatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get batch params
func (o *GetBatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBatchName adds the batchName to the get batch params
func (o *GetBatchParams) WithBatchName(batchName string) *GetBatchParams {
	o.SetBatchName(batchName)
	return o
}

// SetBatchName adds the batchName to the get batch params
func (o *GetBatchParams) SetBatchName(batchName string) {
	o.BatchName = batchName
}

// WriteToRequest writes these params to a swagger request
func (o *GetBatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param batchName
	if err := r.SetPathParam("batchName", o.BatchName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
