package config

const (
	App1Name                         = "canarycicd-test1"
	App1Repository                   = "https://github.com/equinor/radix-canarycicd-test-1"
	App1SharedSecret                 = "AnySharedSecret"
	App1Owner                        = "a-user@equinor.com"
	App1Creator                      = "a-user@equinor.com"
	App1Wbs                          = "WBS.APP.1"
	App2Name                         = "canarycicd-test2"
	App2Owner                        = "a-user@equinor.com"
	App2Creator                      = "a-user@equinor.com"
	App2BranchToBuildFrom            = "master"
	App2CommitID                     = "580f3ae3c0c23503a7cd02a8b60a5dec49279d0f"
	App2Repository                   = "https://github.com/equinor/radix-canarycicd-test-2"
	App2SSHRepository                = "git@github.com:equinor/radix-canarycicd-test-2.git"
	App2SharedSecret                 = "a sportless strobic spinach"
	App2EnvironmentName              = "prod"
	App2Component1Name               = "app"
	App2Component2Name               = "redis"
	App2ComponentPrivateImageHubName = "from-private-image-hub"
	App2SecretName                   = "DB_PASS"
	App2SecretValue                  = "Test"
	App2Wbs                          = "WBS.APP.2"
	App3Name                         = "canarycicd-test3"
	App3Owner                        = "a-user@equinor.com"
	App3Creator                      = "a-user@equinor.com"
	App3BranchToBuildFrom            = "master"
	App3CommitID                     = "580f3ae3c0c23503a7cd02a8b60a5dec49279d0f"
	App3Repository                   = "https://github.com/equinor/radix-canarycicd-test-3"
	App3SSHRepository                = "git@github.com:equinor/radix-canarycicd-test-3.git"
	App3SharedSecret                 = "a sportless strobic spinach"
	App3EnvironmentName              = "prod"
	App3Component1Name               = "client"
	App3Wbs                          = "WBS.APP.3"
	RestrictedApplicationName        = "radix-api"
)
