// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ChangeEnvironmentComponentSecretReader is a Reader for the ChangeEnvironmentComponentSecret structure.
type ChangeEnvironmentComponentSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeEnvironmentComponentSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChangeEnvironmentComponentSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewChangeEnvironmentComponentSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewChangeEnvironmentComponentSecretUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewChangeEnvironmentComponentSecretNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewChangeEnvironmentComponentSecretConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewChangeEnvironmentComponentSecretOK creates a ChangeEnvironmentComponentSecretOK with default headers values
func NewChangeEnvironmentComponentSecretOK() *ChangeEnvironmentComponentSecretOK {
	return &ChangeEnvironmentComponentSecretOK{}
}

/* ChangeEnvironmentComponentSecretOK describes a response with status code 200, with default header values.

success
*/
type ChangeEnvironmentComponentSecretOK struct {
}

func (o *ChangeEnvironmentComponentSecretOK) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/environments/{envName}/components/{componentName}/secrets/{secretName}][%d] changeEnvironmentComponentSecretOK ", 200)
}

func (o *ChangeEnvironmentComponentSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeEnvironmentComponentSecretBadRequest creates a ChangeEnvironmentComponentSecretBadRequest with default headers values
func NewChangeEnvironmentComponentSecretBadRequest() *ChangeEnvironmentComponentSecretBadRequest {
	return &ChangeEnvironmentComponentSecretBadRequest{}
}

/* ChangeEnvironmentComponentSecretBadRequest describes a response with status code 400, with default header values.

Invalid application
*/
type ChangeEnvironmentComponentSecretBadRequest struct {
}

func (o *ChangeEnvironmentComponentSecretBadRequest) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/environments/{envName}/components/{componentName}/secrets/{secretName}][%d] changeEnvironmentComponentSecretBadRequest ", 400)
}

func (o *ChangeEnvironmentComponentSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeEnvironmentComponentSecretUnauthorized creates a ChangeEnvironmentComponentSecretUnauthorized with default headers values
func NewChangeEnvironmentComponentSecretUnauthorized() *ChangeEnvironmentComponentSecretUnauthorized {
	return &ChangeEnvironmentComponentSecretUnauthorized{}
}

/* ChangeEnvironmentComponentSecretUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ChangeEnvironmentComponentSecretUnauthorized struct {
}

func (o *ChangeEnvironmentComponentSecretUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/environments/{envName}/components/{componentName}/secrets/{secretName}][%d] changeEnvironmentComponentSecretUnauthorized ", 401)
}

func (o *ChangeEnvironmentComponentSecretUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeEnvironmentComponentSecretNotFound creates a ChangeEnvironmentComponentSecretNotFound with default headers values
func NewChangeEnvironmentComponentSecretNotFound() *ChangeEnvironmentComponentSecretNotFound {
	return &ChangeEnvironmentComponentSecretNotFound{}
}

/* ChangeEnvironmentComponentSecretNotFound describes a response with status code 404, with default header values.

Not found
*/
type ChangeEnvironmentComponentSecretNotFound struct {
}

func (o *ChangeEnvironmentComponentSecretNotFound) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/environments/{envName}/components/{componentName}/secrets/{secretName}][%d] changeEnvironmentComponentSecretNotFound ", 404)
}

func (o *ChangeEnvironmentComponentSecretNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeEnvironmentComponentSecretConflict creates a ChangeEnvironmentComponentSecretConflict with default headers values
func NewChangeEnvironmentComponentSecretConflict() *ChangeEnvironmentComponentSecretConflict {
	return &ChangeEnvironmentComponentSecretConflict{}
}

/* ChangeEnvironmentComponentSecretConflict describes a response with status code 409, with default header values.

Conflict
*/
type ChangeEnvironmentComponentSecretConflict struct {
}

func (o *ChangeEnvironmentComponentSecretConflict) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/environments/{envName}/components/{componentName}/secrets/{secretName}][%d] changeEnvironmentComponentSecretConflict ", 409)
}

func (o *ChangeEnvironmentComponentSecretConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
