// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/equinor/radix-cicd-canary-golang/generated-client/models"
)

// GetApplicationEnvironmentDeploymentsReader is a Reader for the GetApplicationEnvironmentDeployments structure.
type GetApplicationEnvironmentDeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationEnvironmentDeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetApplicationEnvironmentDeploymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetApplicationEnvironmentDeploymentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetApplicationEnvironmentDeploymentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApplicationEnvironmentDeploymentsOK creates a GetApplicationEnvironmentDeploymentsOK with default headers values
func NewGetApplicationEnvironmentDeploymentsOK() *GetApplicationEnvironmentDeploymentsOK {
	return &GetApplicationEnvironmentDeploymentsOK{}
}

/*GetApplicationEnvironmentDeploymentsOK handles this case with default header values.

Successful operation
*/
type GetApplicationEnvironmentDeploymentsOK struct {
	Payload []*models.DeploymentSummary
}

func (o *GetApplicationEnvironmentDeploymentsOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/environments/{envName}/deployments][%d] getApplicationEnvironmentDeploymentsOK  %+v", 200, o.Payload)
}

func (o *GetApplicationEnvironmentDeploymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationEnvironmentDeploymentsUnauthorized creates a GetApplicationEnvironmentDeploymentsUnauthorized with default headers values
func NewGetApplicationEnvironmentDeploymentsUnauthorized() *GetApplicationEnvironmentDeploymentsUnauthorized {
	return &GetApplicationEnvironmentDeploymentsUnauthorized{}
}

/*GetApplicationEnvironmentDeploymentsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetApplicationEnvironmentDeploymentsUnauthorized struct {
}

func (o *GetApplicationEnvironmentDeploymentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/environments/{envName}/deployments][%d] getApplicationEnvironmentDeploymentsUnauthorized ", 401)
}

func (o *GetApplicationEnvironmentDeploymentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationEnvironmentDeploymentsNotFound creates a GetApplicationEnvironmentDeploymentsNotFound with default headers values
func NewGetApplicationEnvironmentDeploymentsNotFound() *GetApplicationEnvironmentDeploymentsNotFound {
	return &GetApplicationEnvironmentDeploymentsNotFound{}
}

/*GetApplicationEnvironmentDeploymentsNotFound handles this case with default header values.

Not found
*/
type GetApplicationEnvironmentDeploymentsNotFound struct {
}

func (o *GetApplicationEnvironmentDeploymentsNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/environments/{envName}/deployments][%d] getApplicationEnvironmentDeploymentsNotFound ", 404)
}

func (o *GetApplicationEnvironmentDeploymentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
