// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/models"
)

// GetApplicationAlertingConfigReader is a Reader for the GetApplicationAlertingConfig structure.
type GetApplicationAlertingConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationAlertingConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationAlertingConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetApplicationAlertingConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetApplicationAlertingConfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetApplicationAlertingConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetApplicationAlertingConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetApplicationAlertingConfigOK creates a GetApplicationAlertingConfigOK with default headers values
func NewGetApplicationAlertingConfigOK() *GetApplicationAlertingConfigOK {
	return &GetApplicationAlertingConfigOK{}
}

/*GetApplicationAlertingConfigOK handles this case with default header values.

Successful get alerts config
*/
type GetApplicationAlertingConfigOK struct {
	Payload *models.AlertingConfig
}

func (o *GetApplicationAlertingConfigOK) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/alerting][%d] getApplicationAlertingConfigOK  %+v", 200, o.Payload)
}

func (o *GetApplicationAlertingConfigOK) GetPayload() *models.AlertingConfig {
	return o.Payload
}

func (o *GetApplicationAlertingConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationAlertingConfigUnauthorized creates a GetApplicationAlertingConfigUnauthorized with default headers values
func NewGetApplicationAlertingConfigUnauthorized() *GetApplicationAlertingConfigUnauthorized {
	return &GetApplicationAlertingConfigUnauthorized{}
}

/*GetApplicationAlertingConfigUnauthorized handles this case with default header values.

Unauthorized
*/
type GetApplicationAlertingConfigUnauthorized struct {
}

func (o *GetApplicationAlertingConfigUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/alerting][%d] getApplicationAlertingConfigUnauthorized ", 401)
}

func (o *GetApplicationAlertingConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationAlertingConfigForbidden creates a GetApplicationAlertingConfigForbidden with default headers values
func NewGetApplicationAlertingConfigForbidden() *GetApplicationAlertingConfigForbidden {
	return &GetApplicationAlertingConfigForbidden{}
}

/*GetApplicationAlertingConfigForbidden handles this case with default header values.

Forbidden
*/
type GetApplicationAlertingConfigForbidden struct {
}

func (o *GetApplicationAlertingConfigForbidden) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/alerting][%d] getApplicationAlertingConfigForbidden ", 403)
}

func (o *GetApplicationAlertingConfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationAlertingConfigNotFound creates a GetApplicationAlertingConfigNotFound with default headers values
func NewGetApplicationAlertingConfigNotFound() *GetApplicationAlertingConfigNotFound {
	return &GetApplicationAlertingConfigNotFound{}
}

/*GetApplicationAlertingConfigNotFound handles this case with default header values.

Not found
*/
type GetApplicationAlertingConfigNotFound struct {
}

func (o *GetApplicationAlertingConfigNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/alerting][%d] getApplicationAlertingConfigNotFound ", 404)
}

func (o *GetApplicationAlertingConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetApplicationAlertingConfigInternalServerError creates a GetApplicationAlertingConfigInternalServerError with default headers values
func NewGetApplicationAlertingConfigInternalServerError() *GetApplicationAlertingConfigInternalServerError {
	return &GetApplicationAlertingConfigInternalServerError{}
}

/*GetApplicationAlertingConfigInternalServerError handles this case with default header values.

Internal server error
*/
type GetApplicationAlertingConfigInternalServerError struct {
}

func (o *GetApplicationAlertingConfigInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applications/{appName}/alerting][%d] getApplicationAlertingConfigInternalServerError ", 500)
}

func (o *GetApplicationAlertingConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
