// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartApplicationParams creates a new StartApplicationParams object
// with the default values initialized.
func NewStartApplicationParams() *StartApplicationParams {
	var ()
	return &StartApplicationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartApplicationParamsWithTimeout creates a new StartApplicationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartApplicationParamsWithTimeout(timeout time.Duration) *StartApplicationParams {
	var ()
	return &StartApplicationParams{

		timeout: timeout,
	}
}

// NewStartApplicationParamsWithContext creates a new StartApplicationParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartApplicationParamsWithContext(ctx context.Context) *StartApplicationParams {
	var ()
	return &StartApplicationParams{

		Context: ctx,
	}
}

// NewStartApplicationParamsWithHTTPClient creates a new StartApplicationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartApplicationParamsWithHTTPClient(client *http.Client) *StartApplicationParams {
	var ()
	return &StartApplicationParams{
		HTTPClient: client,
	}
}

/*StartApplicationParams contains all the parameters to send to the API endpoint
for the start application operation typically these are written to a http.Request
*/
type StartApplicationParams struct {

	/*ImpersonateGroup
	  Works only with custom setup of cluster. Allow impersonation of test group (Required if Impersonate-User is set)

	*/
	ImpersonateGroup *string
	/*ImpersonateUser
	  Works only with custom setup of cluster. Allow impersonation of test users (Required if Impersonate-Group is set)

	*/
	ImpersonateUser *string
	/*AppName
	  Name of application

	*/
	AppName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start application params
func (o *StartApplicationParams) WithTimeout(timeout time.Duration) *StartApplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start application params
func (o *StartApplicationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start application params
func (o *StartApplicationParams) WithContext(ctx context.Context) *StartApplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start application params
func (o *StartApplicationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start application params
func (o *StartApplicationParams) WithHTTPClient(client *http.Client) *StartApplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start application params
func (o *StartApplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImpersonateGroup adds the impersonateGroup to the start application params
func (o *StartApplicationParams) WithImpersonateGroup(impersonateGroup *string) *StartApplicationParams {
	o.SetImpersonateGroup(impersonateGroup)
	return o
}

// SetImpersonateGroup adds the impersonateGroup to the start application params
func (o *StartApplicationParams) SetImpersonateGroup(impersonateGroup *string) {
	o.ImpersonateGroup = impersonateGroup
}

// WithImpersonateUser adds the impersonateUser to the start application params
func (o *StartApplicationParams) WithImpersonateUser(impersonateUser *string) *StartApplicationParams {
	o.SetImpersonateUser(impersonateUser)
	return o
}

// SetImpersonateUser adds the impersonateUser to the start application params
func (o *StartApplicationParams) SetImpersonateUser(impersonateUser *string) {
	o.ImpersonateUser = impersonateUser
}

// WithAppName adds the appName to the start application params
func (o *StartApplicationParams) WithAppName(appName string) *StartApplicationParams {
	o.SetAppName(appName)
	return o
}

// SetAppName adds the appName to the start application params
func (o *StartApplicationParams) SetAppName(appName string) {
	o.AppName = appName
}

// WriteToRequest writes these params to a swagger request
func (o *StartApplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ImpersonateGroup != nil {

		// header param Impersonate-Group
		if err := r.SetHeaderParam("Impersonate-Group", *o.ImpersonateGroup); err != nil {
			return err
		}

	}

	if o.ImpersonateUser != nil {

		// header param Impersonate-User
		if err := r.SetHeaderParam("Impersonate-User", *o.ImpersonateUser); err != nil {
			return err
		}

	}

	// path param appName
	if err := r.SetPathParam("appName", o.AppName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
