// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateBuildSecretsSecretValueReader is a Reader for the UpdateBuildSecretsSecretValue structure.
type UpdateBuildSecretsSecretValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBuildSecretsSecretValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBuildSecretsSecretValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateBuildSecretsSecretValueBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateBuildSecretsSecretValueUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateBuildSecretsSecretValueNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewUpdateBuildSecretsSecretValueConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateBuildSecretsSecretValueOK creates a UpdateBuildSecretsSecretValueOK with default headers values
func NewUpdateBuildSecretsSecretValueOK() *UpdateBuildSecretsSecretValueOK {
	return &UpdateBuildSecretsSecretValueOK{}
}

/*UpdateBuildSecretsSecretValueOK handles this case with default header values.

success
*/
type UpdateBuildSecretsSecretValueOK struct {
}

func (o *UpdateBuildSecretsSecretValueOK) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/buildsecrets/{secretName}][%d] updateBuildSecretsSecretValueOK ", 200)
}

func (o *UpdateBuildSecretsSecretValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateBuildSecretsSecretValueBadRequest creates a UpdateBuildSecretsSecretValueBadRequest with default headers values
func NewUpdateBuildSecretsSecretValueBadRequest() *UpdateBuildSecretsSecretValueBadRequest {
	return &UpdateBuildSecretsSecretValueBadRequest{}
}

/*UpdateBuildSecretsSecretValueBadRequest handles this case with default header values.

Invalid application
*/
type UpdateBuildSecretsSecretValueBadRequest struct {
}

func (o *UpdateBuildSecretsSecretValueBadRequest) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/buildsecrets/{secretName}][%d] updateBuildSecretsSecretValueBadRequest ", 400)
}

func (o *UpdateBuildSecretsSecretValueBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateBuildSecretsSecretValueUnauthorized creates a UpdateBuildSecretsSecretValueUnauthorized with default headers values
func NewUpdateBuildSecretsSecretValueUnauthorized() *UpdateBuildSecretsSecretValueUnauthorized {
	return &UpdateBuildSecretsSecretValueUnauthorized{}
}

/*UpdateBuildSecretsSecretValueUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateBuildSecretsSecretValueUnauthorized struct {
}

func (o *UpdateBuildSecretsSecretValueUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/buildsecrets/{secretName}][%d] updateBuildSecretsSecretValueUnauthorized ", 401)
}

func (o *UpdateBuildSecretsSecretValueUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateBuildSecretsSecretValueNotFound creates a UpdateBuildSecretsSecretValueNotFound with default headers values
func NewUpdateBuildSecretsSecretValueNotFound() *UpdateBuildSecretsSecretValueNotFound {
	return &UpdateBuildSecretsSecretValueNotFound{}
}

/*UpdateBuildSecretsSecretValueNotFound handles this case with default header values.

Not found
*/
type UpdateBuildSecretsSecretValueNotFound struct {
}

func (o *UpdateBuildSecretsSecretValueNotFound) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/buildsecrets/{secretName}][%d] updateBuildSecretsSecretValueNotFound ", 404)
}

func (o *UpdateBuildSecretsSecretValueNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateBuildSecretsSecretValueConflict creates a UpdateBuildSecretsSecretValueConflict with default headers values
func NewUpdateBuildSecretsSecretValueConflict() *UpdateBuildSecretsSecretValueConflict {
	return &UpdateBuildSecretsSecretValueConflict{}
}

/*UpdateBuildSecretsSecretValueConflict handles this case with default header values.

Conflict
*/
type UpdateBuildSecretsSecretValueConflict struct {
}

func (o *UpdateBuildSecretsSecretValueConflict) Error() string {
	return fmt.Sprintf("[PUT /applications/{appName}/buildsecrets/{secretName}][%d] updateBuildSecretsSecretValueConflict ", 409)
}

func (o *UpdateBuildSecretsSecretValueConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
