// Code generated by go-swagger; DO NOT EDIT.

package platform

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/equinor/radix-cicd-canary/generated-client/radixapi/models"
)

// ShowApplicationsReader is a Reader for the ShowApplications structure.
type ShowApplicationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShowApplicationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShowApplicationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewShowApplicationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewShowApplicationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewShowApplicationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewShowApplicationsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewShowApplicationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShowApplicationsOK creates a ShowApplicationsOK with default headers values
func NewShowApplicationsOK() *ShowApplicationsOK {
	return &ShowApplicationsOK{}
}

/* ShowApplicationsOK describes a response with status code 200, with default header values.

Successful operation
*/
type ShowApplicationsOK struct {
	Payload []*models.ApplicationSummary
}

func (o *ShowApplicationsOK) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsOK  %+v", 200, o.Payload)
}
func (o *ShowApplicationsOK) GetPayload() []*models.ApplicationSummary {
	return o.Payload
}

func (o *ShowApplicationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShowApplicationsUnauthorized creates a ShowApplicationsUnauthorized with default headers values
func NewShowApplicationsUnauthorized() *ShowApplicationsUnauthorized {
	return &ShowApplicationsUnauthorized{}
}

/* ShowApplicationsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ShowApplicationsUnauthorized struct {
}

func (o *ShowApplicationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsUnauthorized ", 401)
}

func (o *ShowApplicationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewShowApplicationsForbidden creates a ShowApplicationsForbidden with default headers values
func NewShowApplicationsForbidden() *ShowApplicationsForbidden {
	return &ShowApplicationsForbidden{}
}

/* ShowApplicationsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ShowApplicationsForbidden struct {
}

func (o *ShowApplicationsForbidden) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsForbidden ", 403)
}

func (o *ShowApplicationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewShowApplicationsNotFound creates a ShowApplicationsNotFound with default headers values
func NewShowApplicationsNotFound() *ShowApplicationsNotFound {
	return &ShowApplicationsNotFound{}
}

/* ShowApplicationsNotFound describes a response with status code 404, with default header values.

Not found
*/
type ShowApplicationsNotFound struct {
}

func (o *ShowApplicationsNotFound) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsNotFound ", 404)
}

func (o *ShowApplicationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewShowApplicationsConflict creates a ShowApplicationsConflict with default headers values
func NewShowApplicationsConflict() *ShowApplicationsConflict {
	return &ShowApplicationsConflict{}
}

/* ShowApplicationsConflict describes a response with status code 409, with default header values.

Conflict
*/
type ShowApplicationsConflict struct {
}

func (o *ShowApplicationsConflict) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsConflict ", 409)
}

func (o *ShowApplicationsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewShowApplicationsInternalServerError creates a ShowApplicationsInternalServerError with default headers values
func NewShowApplicationsInternalServerError() *ShowApplicationsInternalServerError {
	return &ShowApplicationsInternalServerError{}
}

/* ShowApplicationsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ShowApplicationsInternalServerError struct {
}

func (o *ShowApplicationsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applications][%d] showApplicationsInternalServerError ", 500)
}

func (o *ShowApplicationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
