name: radix-cicd-canary-build
on:
  push:
    branches:
      - master
      - release
jobs:
  build:
    name: Build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: radixdev.azurecr.io
      - name: Build docker image
        run: docker build -t radix-cicd-canary:${{ github.branch }}-latest .
