name: radix-cicd-canary-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build:
    name: Build-push
    env:
      IMAGE: radix-cicd-canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - run: |
          docker build . -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Login to ACR radixcanary'
        run: |
          az acr login --name radixcanary
       - name: push release to radixcanary
        run: |
          docker push radixcanary.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
