name: radix-cicd-canary-build
on:
  push:
    branches:
      - master
      - release
jobs:
  build:
    name: Build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Azure
        uses: Azure/github-actions/login@master
        env:
          AZURE_SUBSCRIPTION: "Omnia Radix Development"
          AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
          AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
          AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
      - name: Build docker image
        run: docker build -t radix-cicd-canary:${{ github.branch }}-latest .
