name: radix-cicd-canary-pr
on:
  pull_request:
    branches:
    - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Install GolangCI Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
      - name: Install StaticCheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.6

      - name: golangci-lint
        run: golangci-lint run --timeout=30m --max-same-issues=0 --out-format=github-actions

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-cicd-canary:${REF##*/} .
