name: start-canary
on:
  workflow_dispatch:
  push:
    branches:
      - 259748-schedule-scaling-of-cicd-canary

permissions:
  id-token: write

jobs:
  start-canary:
    name: Start radix-cicd-canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: cd30b7bc-24f7-4887-948a-82ff1c0a2646
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - uses: azure/use-kubelogin@v1
        name: 'Download AKS kubeconfig'
        with:
          kubelogin-version: 'latest'
        run: |
          az aks get-credentials --name weekly-51 --resource-group clusters --subscription 16ede44b-1f74-40a5-b428-46cca9a5741b --format exec --overwrite-existing
      - name: scale-to-one
        run: |
          kubectl scale deployment radix-cicd-canary --replicas=1 -n radix-cicd-canary